version: "^3.0"

services:
  vue-notes:
    image: node:latest
    container_name: vue-notes-front
    working_dir: /home/node/app
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/home/node/app
    ports:
      - "8081:8080"
    networks:
      - notes_default_network

networks:
  notes_default_network:
    name: notes_default_network
